apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80           # Exposed on the cluster
      targetPort: 3000   # The port your React app actually listens on
  type: NodePort
